type: object
additionalProperties: false
properties:
  meta:
    $ref: '../../_index.yaml#/schemas/ResourceMetaDetail'
  spec:
    type: object
    x-required: mandatory
    additionalProperties: false
    properties:
      chainId:
        type: string
        x-required: mandatory
        description: |
          The chain identifier with which the application interacts. It must be a valid integer.
      description:
        type: string
        x-required: mandatory
        description: |
          Description of the resource.
    required:
      - chainId
      - description

example:
  meta:
    id: 'application-1'
    resourceVersion: '7e032829-249d-4498-aa3e-344a16cd6a93'
    creationDate: '1581675232372'
    lastUpdate: '1581675232372'
  spec:
    chainId: '44844'
    description: 'my application'

required:
  - meta
  - spec
