allOf:
  - type: object
    properties:
      items:
        type: array
        x-required: mandatory
        description: collection of applications.
        items:
          $ref: '../../_index.yaml#/schemas/ApplicationDetail'
    required:
      - items
  - $ref: '../../_index.yaml#/schemas/CollectionPage'