type: object
additionalProperties: false
properties:
  meta:
    $ref: '../../_index.yaml#/schemas/ResourceMetaCreation'
  spec:
    type: object
    x-required: mandatory
    nullable: false
    additionalProperties: false
    properties:
      chainId:
        type: string
        x-required: mandatory
        nullable: false
        description: |
          The chain identifier with which the application will interact. It must be a valid integer.
      description:
        type: string
        x-required: optional
        nullable: true
        maxLength: 256
        description: |
          Description of the resource.
    required:
      - chainId

example:
  meta:
    id: 'application-1'
  spec:
    chainId: '44844'
    description: 'my application'

required:
  - spec
