type: object
additionalProperties: false
properties:
  meta:
    $ref: '../../_index.yaml#/schemas/ResourceMetaUpdate'
  spec:
    type: object
    x-required: optional
    nullable: true
    additionalProperties: false
    properties:
      chainId:
        type: string
        x-required: mandatory
        nullable: false
        description: |
          The chain identifier with which the application interacts. It must be a valid integer.
      description:
        type: string
        x-required: optional
        nullable: true
        maxLength: 256
        description: |
          Description of the resource.
    required:
      - chainId

example:
  meta:
    resourceVersion: '7e032829-249d-4498-aa3e-344a16cd6a93'
  spec:
    chainId: '55966'
    description: 'my application'

required:
  - meta
  - spec