openapi: 3.0.0
info:
  title: signare public API spec
  description: signare public API spec
  version: 1.0.0

servers:
  - url: http://localhost:34343
    description: Local test
tags:
  - name: Admin
    description: signare global management services.
  - name: Application
    description: signare application's management services.

paths:
  $ref: ./paths/_index.yaml
components:
  $ref: ./components/_index.yaml
